name: Generate Blog Content

on:
  schedule:
    # Run every Sunday at 2 AM UTC (adjust as needed)
    - cron: '0 2 * * 0'
  workflow_dispatch:  # Allow manual triggering
    inputs:
      batch_size:
        description: 'Number of posts to process (default: all remaining)'
        required: false
        default: '0'
        type: string
      test_mode:
        description: 'Test mode - only process first 3 posts'
        required: false
        default: false
        type: boolean

# Give the workflow permission to write to the repository
permissions:
  contents: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai
    
    - name: Generate blog content
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python generate_blog_content.py
    
    - name: Rebuild index with sorted posts
      run: |
        python build_index.py
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add posts/*.html
        git add generated_content.json
        git add index.html
        git commit -m "Generate authentic blog content via GitHub Actions

        🤖 Generated with Claude Code + OpenAI GPT-4o
        
        Co-Authored-By: Claude <noreply@anthropic.com>"
        git push
    
    - name: Upload generated content artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: generated-content
        path: |
          generated_content.json
          *.log
        retention-days: 30